version: '3.8'
services:
  validator:
    image: chronollm/sn38-validator@sha256:92ad352e2eea1be38702612dac257de3a72b41bdffef7c0d6932cf89d537ce1d
    restart: "on-failure"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - validator-data:/app/data
    environment:
      - NETUID=38
      - SUBTENSOR_NETWORK=finney
      - BACKEND_URL=https://api.chronollm.com
      # This secret is encrypted client-side by Phala CLI before transmission
      - HOTKEY_FILE_CONTENT=${HOTKEY_FILE_CONTENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_DEBUG=${HF_DEBUG:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  validator-data:
