version: '3.8'
services:
  validator:
    image: chronollm/sn38-validator@sha256:3f8192b14d8860aa85db6d5e7a1cb9836b6794b67e48e6656490c6f3eee341fc
    restart: "no"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - validator-data:/app/data
    environment:
      - NETUID=38
      - SUBTENSOR_NETWORK=finney
      - BACKEND_URL=https://api.chronollm.com
      # This secret is encrypted client-side by Phala CLI before transmission
      - HOTKEY_FILE_CONTENT=${HOTKEY_FILE_CONTENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_DEBUG=${HF_DEBUG:-1}
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

volumes:
  validator-data:
