version: '3.8'
services:
  self-test:
    image: chronollm/sn38-validator@sha256:7e49c8cca8a27f00ffb391d52efe63ef88a1160ef4d7a040e9b4fc34990621a5
    restart: "on-failure"
    ports:
      - "8081:8081"
    environment:
      - WALLET_NAME=miner
      - BACKEND_URL=https://api.chronollm.com
      # This secret is encrypted client-side by Phala CLI before transmission
      - HOTKEY_FILE_CONTENT=${HOTKEY_FILE_CONTENT}
      - HF_TOKEN=${HF_TOKEN}
      - HF_REPO=${HF_REPO}
    command: ["python", "-m", "sn38.neurons.miner_leak_test", "--repo", "${HF_REPO}"]
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - self-test-cache:/tmp/model-cache

volumes:
  self-test-cache:
